### PR TITLE
Commonjsify

### PR DESCRIPTION
**Pull request by akre54**
The localstorage-events package needs a `name` field, breaking npm install currently.

### CODE REVIEW

**Comment by mponizil** [comment]
Woo!

You should be a collaborator on `localstorage-events` now (if the bower adapter works that's cool, I'm on board w/ going pure npm everywhere but not a huge deal).

Realizing now this will probably be a royal pain and I should have mentioned in the TODO, but there's a handful of random tweaks / ideas on the [sketch](https://github.com/chatid/iframe-transport/tree/sketch) branch. I think I only held off merging cuz of broken tests and a few small incomplete areas...

What do you think of merging this and then manually re-implementing the changes? Primary changes are renaming `Courier` -> `Manager`, dropping global service registry, and enforcing channel namespaces.

https://github.com/chatid/iframe-transport/compare/master...sketch

Sorry again for the headache, but perhaps this could feed well into revamping tests?

**Comment by akre54** [comment]
Yeah I'll try to pull those changes in. Hopefully it won't be a mess to add in manually

**Comment by mponizil** [comment]
Good deal, much appreciated!

**Comment by mponizil** [comment]
Closing in favor of #4

**Pull request closed without merging**
